# Generated by Django 4.0.1 on 2022-01-29 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='user_contact',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
