# Generated by Django 4.0.1 on 2022-01-29 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact_user_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='user_contact',
            new_name='user',
        ),
    ]
